[-] Fix: OrderHistory::changeIdOrderState
&$id_order break compatibility with existing codes :

1/ it's unnecessary : Objects are passed by references by default
2/ it causes fatal errors: 
```PHP
$foo->changeIdOrderState((int)$id_order_state, (int)$id_order);
```
Fatal error: Only variables can be passed by reference