added getPagination to core PdfTemplate
Seen that there is a [call to getPagination on each render of a pdf](https://github.com/PrestaShop/PrestaShop/blob/1.6.1.x/classes/pdf/PDF.php#L95)  I propose that it is added to the core template file.

because when I try to generate a pdf (other then invoice) now I get this error: (using prestashop 1.6.1.5)

```
Fatal error: Call to undefined method HTMLTemplateOrderReturn::getPagination() in /var/www/html/classes/pdf/PDF.php on line 95
Fatal error: Call to undefined method HTMLTemplateDeliverySlip::getPagination() in /var/www/html/classes/pdf/PDF.php on line 95
```